###########################################################
#   Description: Compile work by GitHub Actions      #
#   Based on:    										  #
#   Author: Teasiu                                        #
###########################################################

name: autoworkmv200

on:
  repository_dispatch:
  workflow_dispatch:

  schedule:
    - cron: 0 5 * * *

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential zlib1g-dev bison flex libncurses-dev
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo rm -rf /bin/sh
        sudo ln -s /bin/bash /bin/sh

#    - name: Start SSH via tmate
#      uses: P3TERX/ssh2actions@main
#      env:
#        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        
    - name: clone repo and make
      run: |
        git clone ${{ secrets.WORK }} work
        cd work
        ls -al
        bash mv200.sh -a
        bash mv200.sh -b
        bash mv200.sh -c
        bash mv200.sh -e
        bash mv200.sh -g
        bash mv200.sh -p
        bash mv200-64.sh -a
        bash mv200-64.sh -b
        bash mv200-64.sh -c
        bash mv200-64.sh -e
        bash mv200-64.sh -g
        bash mv200-64.sh -p

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "./work/out/hi3798mv200/"
        server-dir: "mv200/"
